const loader=document.getElementById("loader");window.addEventListener("load",()=>setTimeout(()=>loader.classList.add("done"),1550));
const cursor=document.getElementById("cursor");
if(window.matchMedia("(pointer:fine)").matches){window.addEventListener("pointermove",e=>{cursor.style.left=e.clientX+"px";cursor.style.top=e.clientY+"px";document.querySelectorAll(".float").forEach(el=>{const d=Number(el.dataset.depth||1);el.style.marginLeft=((e.clientX-innerWidth/2)/innerWidth*d*18)+"px";el.style.marginTop=((e.clientY-innerHeight/2)/innerHeight*d*18)+"px"})});document.querySelectorAll("a,button,.polaroid,.memory-photo,.chole-window").forEach(el=>{el.addEventListener("mouseenter",()=>cursor.classList.add("hover"));el.addEventListener("mouseleave",()=>cursor.classList.remove("hover"))})}else cursor.style.display="none";
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.15});document.querySelectorAll(".reveal").forEach(x=>io.observe(x));
document.querySelectorAll(".magnetic").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener("pointerleave",()=>el.style.transform="")});
const soundToggle=document.getElementById("soundToggle");let sound=false;soundToggle.addEventListener("click",()=>{sound=!sound;soundToggle.querySelector("span").textContent=sound?"on":"off"});
document.querySelectorAll(".fake-player").forEach(btn=>btn.addEventListener("click",()=>{btn.querySelector("span").textContent="●";btn.querySelector("small").textContent="áudio pendente"}));
const stage=document.querySelector(".chole-window");if(stage){stage.addEventListener("pointermove",e=>{const r=stage.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;stage.style.transform=`scale(1.02) translate(${x*9}px,${y*9}px)`});stage.addEventListener("pointerleave",()=>stage.style.transform="")};
window.addEventListener("scroll",()=>{document.documentElement.style.setProperty("--scroll",window.scrollY)});
